# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance', '0002_auto_20160813_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='screenname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
