# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance', '0003_auto_20160813_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
