# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_finance', '0004_auto_20160813_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('travel', 'Путешествия'), ('restaurants', 'Рестораны и кафе'), ('transport', 'Транспорт'), ('internet', 'Интернет'), ('mobile', 'Мобильная связь'), ('stores', 'Магазины'), ('products', 'Еда и напитки'), ('another', 'Другое')], default='', max_length=200),
        ),
    ]
